### ISSUE TITLE
Can't build without having dmd/bin being part of environment path variable.

### ISSUE THREAD

**Issue by 12345swordy** [rainers/dlangvs#2]
This isn't ideal, as I rely on visual d to auto update the dmd compiler.

**Comment by rainers** [comment]
No sure what step you mean, dmd is built with the compiler configured in Visual D, and the rest with the generated compiler.
The test suite might use the host compiler, too, but AFAICT that used to work, too.

**Comment by 12345swordy** [comment]
When it attempts to build it without having dmd/bin part of the path variable, it complains about not finding object.d or that the import fails. Want me to post the error messages for you?

**Comment by rainers** [comment]
Not sure if it helps but I pushed some uncommitted local changes.
If not, yes, please post the messages.

**Comment by 12345swordy** [comment]
I think the recent changes fixes it. Thank you.
